//
//  BluetoothIDs.swift
//  wvfBluetooth
//
//  Created by Joseph A. Bennett on 6/11/20.
//  Copyright © 2020 Joseph A Bennett. All rights reserved.
//

import Foundation
import CoreBluetooth

enum org_bluetooth_service: String {
	case generic_access					= "1800"
	case device_information				= "180A"
	case alert_notification				= "1811"
	case automation_io					= "1815"
	case battery_service				= "180F"
	case blood_pressure					= "1810"
	case body_composition				= "181B"
	case bond_management				= "181E"
	case continuous_glucose_monitoring	= "181F"
	case current_time					= "1805"
	case cycling_power					= "1818"
	case cycling_speed_and_cadence		= "1816"
	case environmental_sensing			= "181A"
	case fitness_machine				= "1826"
	case generic_attribute				= "1801"
	case glucose						= "1808"
	case health_thermometer				= "1809"
	case heart_rate						= "180D"
	case http_proxy						= "1823"
	case human_interface_device			= "1812"
	case immediate_alert				= "1802"
	case indoor_positioning				= "1821"
	case insulin_delivery				= "183A"
	case internet_protocol_support		= "1820"
	case link_loss						= "1803"
	case location_and_navigation		= "1819"
	case mesh_provisioning				= "1827"
	case mesh_proxy						= "1828"
	case next_dst_change				= "1807"
	case object_transfer				= "1825"
	case phone_alert_status				= "180E"
	case pulse_oximeter					= "1822"
	case reconnection_configuration		= "1829"
	case reference_time_update			= "1806"
	case running_speed_and_cadence		= "1814"
	case scan_parameters				= "1813"
	case transport_discovery			= "1824"
	case tx_power						= "1804"
	case user_data						= "181C"
	case weight_scale					= "181D"
	
	var UUID: CBUUID {
		return CBUUID(string: self.rawValue)
	}
	
	var title: String {
		switch (self) {
			case .generic_access				: return "Generic Access"
			case .alert_notification			: return "Alert Notification Service"
			case .automation_io					: return "Automation IO"
			case .battery_service				: return "Battery Service"
			case .blood_pressure				: return "Blood Pressure"
			case .body_composition				: return "Body Composition"
			case .bond_management				: return "Bond Management Service"
			case .continuous_glucose_monitoring	: return "Continuous Glucose Monitoring"
			case .current_time					: return "Current Time Service"
			case .cycling_power					: return "Cycling Power"
			case .cycling_speed_and_cadence		: return "Cycling Speed and Cadence"
			case .device_information			: return "Device Information"
			case .environmental_sensing			: return "Environmental Sensing"
			case .fitness_machine				: return "Fitness Machine"
			case .generic_attribute				: return "Generic Attribute"
			case .glucose						: return "Glucose"
			case .health_thermometer			: return "Health Thermometer"
			case .heart_rate					: return "Heart Rate"
			case .http_proxy					: return "HTTP Proxy"
			case .human_interface_device		: return "Human Interface Device"
			case .immediate_alert				: return "Immediate Alert"
			case .indoor_positioning			: return "Indoor Positioning"
			case .insulin_delivery				: return "Insulin Delivery"
			case .internet_protocol_support		: return "Internet Protocol Support Service"
			case .link_loss						: return "Link Loss"
			case .location_and_navigation		: return "Location and Navigation"
			case .mesh_provisioning				: return "Mesh Provisioning Service"
			case .mesh_proxy					: return "Mesh Proxy Service"
			case .next_dst_change				: return "Next DST Change Service"
			case .object_transfer				: return "Object Transfer Service"
			case .phone_alert_status			: return "Phone Alert Status Service"
			case .pulse_oximeter				: return "Pulse Oximeter Service"
			case .reconnection_configuration	: return "Reconnection Configuration"
			case .reference_time_update			: return "Reference Time Update Service"
			case .running_speed_and_cadence		: return "Running Speed and Cadence"
			case .scan_parameters				: return "Scan Parameters"
			case .transport_discovery			: return "Transport Discovery"
			case .tx_power						: return "Tx Power"
			case .user_data						: return "User Data"
			case .weight_scale					: return "Weight Scale"
		}
	}
}

enum org_bluetooth_characteristic: String {
	case aerobic_heart_rate_lower_limit						= "2A7E"
	case aerobic_heart_rate_upper_limit						= "2A84"
	case aerobic_threshold									= "2A7F"
	case age												= "2A80"
	case aggregate											= "2A5A"
	case alert_category_id									= "2A43"
	case alert_category_id_bit_mask							= "2A42"
	case alert_level										= "2A06"
	case alert_notification_control_point					= "2A44"
	case alert_status										= "2A3F"
	case altitude											= "2AB3"
	case anaerobic_heart_rate_lower_limit					= "2A81"
	case anaerobic_heart_rate_upper_limit					= "2A82"
	case anaerobic_threshold								= "2A83"
	case analog												= "2A58"
	case analog_output										= "2A59"
	case apparent_wind_direction							= "2A73"
	case apparent_wind_speed								= "2A72"
	case gap_appearance										= "2A01"
	case barometric_pressure_trend							= "2AA3"
	case battery_level										= "2A19"
	case battery_level_state								= "2A1B"
	case battery_power_state								= "2A1A"
	case blood_pressure_feature								= "2A49"
	case blood_pressure_measurement							= "2A35"
	case body_composition_feature							= "2A9B"
	case body_composition_measurement						= "2A9C"
	case body_sensor_location								= "2A38"
	case bond_management_control_point						= "2AA4"
	case bond_management_feature							= "2AA5"
	case boot_keyboard_input_report							= "2A22"
	case boot_keyboard_output_report						= "2A32"
	case boot_mouse_input_report							= "2A33"
	case cgm_feature										= "2AA8"
	case cgm_measurement									= "2AA7"
	case cgm_session_run_time								= "2AAB"
	case cgm_session_start_time								= "2AAA"
	case cgm_specific_ops_control_point						= "2AAC"
	case cgm_status											= "2AA9"
	case cross_trainer_data									= "2ACE"
	case csc_feature										= "2A5C"
	case csc_measurement									= "2A5B"
	case current_time										= "2A2B"
	case cycling_power_control_point						= "2A66"
	case cycling_power_feature								= "2A65"
	case cycling_power_measurement							= "2A63"
	case cycling_power_vector								= "2A64"
	case database_change_increment							= "2A99"
	case date_of_birth										= "2A85"
	case date_of_threshold_assessment						= "2A86"
	case date_time											= "2A08"
	case date_utc											= "2AED"
	case day_date_time										= "2A0A"
	case day_of_week										= "2A09"
	case descriptor_value_changed							= "2A7D"
	case dew_point											= "2A7B"
	case digital											= "2A56"
	case digital_output										= "2A57"
	case dst_offset											= "2A0D"
	case elevation											= "2A6C"
	case email_address										= "2A87"
	case exact_time_100										= "2A0B"
	case exact_time_256										= "2A0C"
	case fat_burn_heart_rate_lower_limit					= "2A88"
	case fat_burn_heart_rate_upper_limit					= "2A89"
	case firmware_revision_string							= "2A26"
	case first_name											= "2A8A"
	case fitness_machine_control_point						= "2AD9"
	case fitness_machine_feature							= "2ACC"
	case fitness_machine_status								= "2ADA"
	case five_zone_heart_rate_limits						= "2A8B"
	case floor_number										= "2AB2"
	case gap_central_address_resolution						= "2AA6"
	case gap_device_name									= "2A00"
	case gap_peripheral_preferred_connection_parameters		= "2A04"
	case gap_peripheral_privacy_flag						= "2A02"
	case gap_reconnection_address							= "2A03"
	case gatt_service_changed								= "2A05"
	case gender												= "2A8C"
	case glucose_feature									= "2A51"
	case glucose_measurement								= "2A18"
	case glucose_measurement_context						= "2A34"
	case gust_factor										= "2A74"
	case hardware_revision_string							= "2A27"
	case heart_rate_control_point							= "2A39"
	case heart_rate_max										= "2A8D"
	case heart_rate_measurement								= "2A37"
	case heat_index											= "2A7A"
	case height												= "2A8E"
	case hid_control_point									= "2A4C"
	case hid_information									= "2A4A"
	case hip_circumference									= "2A8F"
	case http_control_point									= "2ABA"
	case http_entity_body									= "2AB9"
	case http_headers										= "2AB7"
	case http_status_code									= "2AB8"
	case https_security										= "2ABB"
	case humidity											= "2A6F"
	case idd_annunciation_status							= "2B22"
	case idd_command_control_point							= "2B25"
	case idd_command_data									= "2B26"
	case idd_features										= "2B23"
	case idd_history_data									= "2B28"
	case idd_record_access_control_point					= "2B27"
	case idd_status											= "2B21"
	case idd_status_changed									= "2B20"
	case idd_status_reader_control_point					= "2B24"
	case ieee_11073_20601_regulatory_certification_data_list	= "2A2A"
	case indoor_bike_data									= "2AD2"
	case indoor_positioning_configuration					= "2AAD"
	case intermediate_cuff_pressure							= "2A36"
	case intermediate_temperature							= "2A1E"
	case irradiance											= "2A77"
	case language											= "2AA2"
	case last_name											= "2A90"
	case latitude											= "2AAE"
	case ln_control_point									= "2A6B"
	case ln_feature											= "2A6A"
	case local_east_coordinate								= "2AB1"
	case local_north_coordinate								= "2AB0"
	case local_time_information								= "2A0F"
	case location_and_speed									= "2A67"
	case location_name										= "2AB5"
	case Longitude											= "2AAF"
	case magnetic_declination								= "2A2C"
	case Magnetic_flux_density_2D							= "2AA0"
	case Magnetic_flux_density_3D							= "2AA1"
	case manufacturer_name_string							= "2A29"
	case maximum_recommended_heart_rate						= "2A91"
	case measurement_interval								= "2A21"
	case model_number_string								= "2A24"
	case navigation											= "2A68"
	case network_availability								= "2A3E"
	case new_alert											= "2A46"
	case object_action_control_point						= "2AC5"
	case object_changed										= "2AC8"
	case object_first_created								= "2AC1"
	case object_id											= "2AC3"
	case object_last_modified								= "2AC2"
	case object_list_control_point							= "2AC6"
	case object_list_filter									= "2AC7"
	case object_name										= "2ABE"
	case object_properties									= "2AC4"
	case object_size										= "2AC0"
	case object_type										= "2ABF"
	case ots_feature										= "2ABD"
	case plx_continuous_measurement							= "2A5F"
	case plx_features										= "2A60"
	case plx_spot_check_measurement							= "2A5E"
	case pnp_id												= "2A50"
	case pollen_concentration								= "2A75"
	case position_2d										= "2A2F"
	case position_3d										= "2A30"
	case position_quality									= "2A69"
	case pressure											= "2A6D"
	case protocol_mode										= "2A4E"
	case pulse_oximetry_control_point						= "2A62"
	case rainfall											= "2A78"
	case rc_feature											= "2B1D"
	case rc_settings										= "2B1E"
	case reconnection_configuration_control_point			= "2B1F"
	case record_access_control_point						= "2A52"
	case reference_time_information							= "2A14"
	case removable											= "2A3A"
	case report												= "2A4D"
	case report_map											= "2A4B"
	case resolvable_private_address_only					= "2AC9"
	case resting_heart_rate									= "2A92"
	case ringer_control_point								= "2A40"
	case ringer_setting										= "2A41"
	case rower_data											= "2AD1"
	case rsc_feature										= "2A54"
	case rsc_measurement									= "2A53"
	case sc_control_point									= "2A55"
	case scan_interval_window								= "2A4F"
	case scan_refresh										= "2A31"
	case scientific_temperature_celsius						= "2A3C"
	case secondary_time_zone								= "2A10"
	case sensor_location									= "2A5D"
	case serial_number_string								= "2A25"
	case service_required									= "2A3B"
	case software_revision_string							= "2A28"
	case sport_type_for_aerobic_and_anaerobic_thresholds	= "2A93"
	case stair_climber_data									= "2AD0"
	case step_climber_data									= "2ACF"
	case string												= "2A3D"
	case supported_heart_rate_range							= "2AD7"
	case supported_inclination_range						= "2AD5"
	case supported_new_alert_category						= "2A47"
	case supported_power_range								= "2AD8"
	case supported_resistance_level_range					= "2AD6"
	case supported_speed_range								= "2AD4"
	case supported_unread_alert_category					= "2A48"
	case system_id											= "2A23"
	case tds_control_point									= "2ABC"
	case temperature										= "2A6E"
	case temperature_celsius								= "2A1F"
	case temperature_fahrenheit								= "2A20"
	case temperature_measurement							= "2A1C"
	case temperature_type									= "2A1D"
	case three_zone_heart_rate_limits						= "2A94"
	case time_accuracy										= "2A12"
	case time_broadcast										= "2A15"
	case time_source										= "2A13"
	case time_update_control_point							= "2A16"
	case time_update_state									= "2A17"
	case time_with_dst										= "2A11"
	case time_zone											= "2A0E"
	case training_status									= "2AD3"
	case treadmill_data										= "2ACD"
	case true_wind_direction								= "2A71"
	case true_wind_speed									= "2A70"
	case two_zone_heart_rate_limit							= "2A95"
	case tx_power_level										= "2A07"
	case uncertainty										= "2AB4"
	case unread_alert_status								= "2A45"
	case uri												= "2AB6"
	case user_control_point									= "2A9F"
	case user_index											= "2A9A"
	case uv_index											= "2A76"
	case vo2_max											= "2A96"
	case waist_circumference								= "2A97"
	case weight												= "2A98"
	case weight_measurement									= "2A9D"
	case weight_scale_feature								= "2A9E"
	case wind_chill											= "2A79"
	
	var UUID: CBUUID {
		return CBUUID(string: self.rawValue)
	}

	var title	: String {
		switch (self) {
			case .aerobic_heart_rate_lower_limit						: return "Aerobic Heart Rate Lower Limit"
			case .aerobic_heart_rate_upper_limit						: return "Aerobic Heart Rate Upper Limit"
			case .aerobic_threshold										: return "Aerobic Threshold"
			case .age													: return "Age"
			case .aggregate												: return "Aggregate"
			case .alert_category_id										: return "Alert Category ID"
			case .alert_category_id_bit_mask							: return "Alert Category ID Bit Mask"
			case .alert_level											: return "Alert Level"
			case .alert_notification_control_point						: return "Alert Notification Control Point"
			case .alert_status											: return "Alert Status"
			case .altitude												: return "Altitude"
			case .anaerobic_heart_rate_lower_limit						: return "Anaerobic Heart Rate Lower Limit"
			case .anaerobic_heart_rate_upper_limit						: return "Anaerobic Heart Rate Upper Limit"
			case .anaerobic_threshold									: return "Anaerobic Threshold"
			case .analog												: return "Analog"
			case .analog_output											: return "Analog Output"
			case .apparent_wind_direction								: return "Apparent Wind Direction"
			case .apparent_wind_speed									: return "Apparent Wind Speed"
			case .gap_appearance										: return "Appearance"
			case .barometric_pressure_trend								: return "Barometric Pressure Trend"
			case .battery_level											: return "Battery Level"
			case .battery_level_state									: return "Battery Level State"
			case .battery_power_state									: return "Battery Power State"
			case .blood_pressure_feature								: return "Blood Pressure Feature"
			case .blood_pressure_measurement							: return "Blood Pressure Measurement"
			case .body_composition_feature								: return "Body Composition Feature"
			case .body_composition_measurement							: return "Body Composition Measurement"
			case .body_sensor_location									: return "Body Sensor Location"
			case .bond_management_control_point							: return "Bond Management Control Point"
			case .bond_management_feature								: return "Bond Management Features"
			case .boot_keyboard_input_report							: return "Boot Keyboard Input Report"
			case .boot_keyboard_output_report							: return "Boot Keyboard Output Report"
			case .boot_mouse_input_report								: return "Boot Mouse Input Report"
			case .cgm_feature											: return "CGM Feature"
			case .cgm_measurement										: return "CGM Measurement"
			case .cgm_session_run_time									: return "CGM Session Run Time"
			case .cgm_session_start_time								: return "CGM Session Start Time"
			case .cgm_specific_ops_control_point						: return "CGM Specific Ops Control Point"
			case .cgm_status											: return "CGM Status"
			case .cross_trainer_data									: return "Cross Trainer Data"
			case .csc_feature											: return "CSC Feature"
			case .csc_measurement										: return "CSC Measurement"
			case .current_time											: return "Current Time"
			case .cycling_power_control_point							: return "Cycling Power Control Point"
			case .cycling_power_feature									: return "Cycling Power Feature"
			case .cycling_power_measurement								: return "Cycling Power Measurement"
			case .cycling_power_vector									: return "Cycling Power Vector"
			case .database_change_increment								: return "Database Change Increment"
			case .date_of_birth											: return "Date of Birth"
			case .date_of_threshold_assessment							: return "Date of Threshold Assessment"
			case .date_time												: return "Date Time"
			case .date_utc												: return "Date UTC"
			case .day_date_time											: return "Day Date Time"
			case .day_of_week											: return "Day of Week"
			case .descriptor_value_changed								: return "Descriptor Value Changed"
			case .dew_point												: return "Dew Point"
			case .digital												: return "Digital"
			case .digital_output										: return "Digital Output"
			case .dst_offset											: return "DST Offset"
			case .elevation												: return "Elevation"
			case .email_address											: return "Email Address"
			case .exact_time_100										: return "Exact Time 100"
			case .exact_time_256										: return "Exact Time 256"
			case .fat_burn_heart_rate_lower_limit						: return "Fat Burn Heart Rate Lower Limit"
			case .fat_burn_heart_rate_upper_limit						: return "Fat Burn Heart Rate Upper Limit"
			case .firmware_revision_string								: return "Firmware Revision String"
			case .first_name											: return "First Name"
			case .fitness_machine_control_point							: return "Fitness Machine Control Point"
			case .fitness_machine_feature								: return "Fitness Machine Feature"
			case .fitness_machine_status								: return "Fitness Machine Status"
			case .five_zone_heart_rate_limits							: return "Five Zone Heart Rate Limits"
			case .floor_number											: return "Floor Number"
			case .gap_central_address_resolution						: return "Central Address Resolution"
			case .gap_device_name										: return "Device Name"
			case .gap_peripheral_preferred_connection_parameters		: return "Peripheral Preferred Connection Parameters"
			case .gap_peripheral_privacy_flag							: return "Peripheral Privacy Flag"
			case .gap_reconnection_address								: return "Reconnection Address"
			case .gatt_service_changed									: return "Service Changed"
			case .gender												: return "Gender"
			case .glucose_feature										: return "Glucose Feature"
			case .glucose_measurement									: return "Glucose Measurement"
			case .glucose_measurement_context							: return "Glucose Measurement Context"
			case .gust_factor											: return "Gust Factor"
			case .hardware_revision_string								: return "Hardware Revision String"
			case .heart_rate_control_point								: return "Heart Rate Control Point"
			case .heart_rate_max										: return "Heart Rate Max"
			case .heart_rate_measurement								: return "Heart Rate Measurement"
			case .heat_index											: return "Heat Index"
			case .height												: return "Height"
			case .hid_control_point										: return "HID Control Point"
			case .hid_information										: return "HID Information"
			case .hip_circumference										: return "Hip Circumference"
			case .http_control_point									: return "HTTP Control Point"
			case .http_entity_body										: return "HTTP Entity Body"
			case .http_headers											: return "HTTP Headers"
			case .http_status_code										: return "HTTP Status Code"
			case .https_security										: return "HTTPS Security"
			case .humidity												: return "Humidity"
			case .idd_annunciation_status								: return "IDD Annunciation Status"
			case .idd_command_control_point								: return "IDD Command Control Point"
			case .idd_command_data										: return "IDD Command Data"
			case .idd_features											: return "IDD Features"
			case .idd_history_data										: return "IDD History Data"
			case .idd_record_access_control_point						: return "IDD Record Access Control Point"
			case .idd_status											: return "IDD Status"
			case .idd_status_changed									: return "IDD Status Changed"
			case .idd_status_reader_control_point						: return "IDD Status Reader Control Point"
			case .ieee_11073_20601_regulatory_certification_data_list	: return "IEEE 11073-20601 Regulatory Certification Data List"
			case .indoor_bike_data										: return "Indoor Bike Data"
			case .indoor_positioning_configuration						: return "Indoor Positioning Configuration"
			case .intermediate_cuff_pressure							: return "Intermediate Cuff Pressure"
			case .intermediate_temperature								: return "Intermediate Temperature"
			case .irradiance											: return "Irradiance"
			case .language												: return "Language"
			case .last_name												: return "Last Name"
			case .latitude												: return "Latitude"
			case .ln_control_point										: return "LN Control Point"
			case .ln_feature											: return "LN Feature"
			case .local_east_coordinate									: return "Local East Coordinate"
			case .local_north_coordinate								: return "Local North Coordinate"
			case .local_time_information								: return "Local Time Information"
			case .location_and_speed									: return "Location and Speed Characteristic"
			case .location_name											: return "Location Name"
			case .Longitude												: return "Longitude"
			case .magnetic_declination									: return "Magnetic Declination"
			case .Magnetic_flux_density_2D								: return "Magnetic Flux Density – 2D"
			case .Magnetic_flux_density_3D								: return "Magnetic Flux Density – 3D"
			case .manufacturer_name_string								: return "Manufacturer Name String"
			case .maximum_recommended_heart_rate						: return "Maximum Recommended Heart Rate"
			case .measurement_interval									: return "Measurement Interval"
			case .model_number_string									: return "Model Number String"
			case .navigation											: return "Navigation"
			case .network_availability									: return "Network Availability"
			case .new_alert												: return "New Alert"
			case .object_action_control_point							: return "Object Action Control Point"
			case .object_changed										: return "Object Changed"
			case .object_first_created									: return "Object First-Created"
			case .object_id												: return "Object ID"
			case .object_last_modified									: return "Object Last-Modified"
			case .object_list_control_point								: return "Object List Control Point"
			case .object_list_filter									: return "Object List Filter"
			case .object_name											: return "Object Name"
			case .object_properties										: return "Object Properties"
			case .object_size											: return "Object Size"
			case .object_type											: return "Object Type"
			case .ots_feature											: return "OTS Feature"
			case .plx_continuous_measurement							: return "PLX Continuous Measurement Characteristic"
			case .plx_features											: return "PLX Features"
			case .plx_spot_check_measurement							: return "PLX Spot-Check Measurement"
			case .pnp_id												: return "PnP ID"
			case .pollen_concentration									: return "Pollen Concentration"
			case .position_2d											: return "Position 2D"
			case .position_3d											: return "Position 3D"
			case .position_quality										: return "Position Quality"
			case .pressure												: return "Pressure"
			case .protocol_mode											: return "Protocol Mode"
			case .pulse_oximetry_control_point							: return "Pulse Oximetry Control Point"
			case .rainfall												: return "Rainfall"
			case .rc_feature											: return "RC Feature"
			case .rc_settings											: return "RC Settings"
			case .reconnection_configuration_control_point				: return "Reconnection Configuration Control Point"
			case .record_access_control_point							: return "Record Access Control Point"
			case .reference_time_information							: return "Reference Time Information"
			case .removable												: return "Removable"
			case .report												: return "Report"
			case .report_map											: return "Report Map"
			case .resolvable_private_address_only						: return "Resolvable Private Address Only"
			case .resting_heart_rate									: return "Resting Heart Rate"
			case .ringer_control_point									: return "Ringer Control point"
			case .ringer_setting										: return "Ringer Setting"
			case .rower_data											: return "Rower Data"
			case .rsc_feature											: return "RSC Feature"
			case .rsc_measurement										: return "RSC Measurement"
			case .sc_control_point										: return "SC Control Point"
			case .scan_interval_window									: return "Scan Interval Window"
			case .scan_refresh											: return "Scan Refresh"
			case .scientific_temperature_celsius						: return "Scientific Temperature Celsius"
			case .secondary_time_zone									: return "Secondary Time Zone"
			case .sensor_location										: return "Sensor Location"
			case .serial_number_string									: return "Serial Number String"
			case .service_required										: return "Service Required"
			case .software_revision_string								: return "Software Revision String"
			case .sport_type_for_aerobic_and_anaerobic_thresholds		: return "Sport Type for Aerobic and Anaerobic Thresholds"
			case .stair_climber_data									: return "Stair Climber Data"
			case .step_climber_data										: return "Step Climber Data"
			case .string												: return "String"
			case .supported_heart_rate_range							: return "Supported Heart Rate Range"
			case .supported_inclination_range							: return "Supported Inclination Range"
			case .supported_new_alert_category							: return "Supported New Alert Category"
			case .supported_power_range									: return "Supported Power Range"
			case .supported_resistance_level_range						: return "Supported Resistance Level Range"
			case .supported_speed_range									: return "Supported Speed Range"
			case .supported_unread_alert_category						: return "Supported Unread Alert Category"
			case .system_id												: return "System ID"
			case .tds_control_point										: return "TDS Control Point"
			case .temperature											: return "Temperature"
			case .temperature_celsius									: return "Temperature Celsius"
			case .temperature_fahrenheit								: return "Temperature Fahrenheit"
			case .temperature_measurement								: return "Temperature Measurement"
			case .temperature_type										: return "Temperature Type"
			case .three_zone_heart_rate_limits							: return "Three Zone Heart Rate Limits"
			case .time_accuracy											: return "Time Accuracy"
			case .time_broadcast										: return "Time Broadcast"
			case .time_source											: return "Time Source"
			case .time_update_control_point								: return "Time Update Control Point"
			case .time_update_state										: return "Time Update State"
			case .time_with_dst											: return "Time with DST"
			case .time_zone												: return "Time Zone"
			case .training_status										: return "Training Status"
			case .treadmill_data										: return "Treadmill Data"
			case .true_wind_direction									: return "True Wind Direction"
			case .true_wind_speed										: return "True Wind Speed"
			case .two_zone_heart_rate_limit								: return "Two Zone Heart Rate Limit"
			case .tx_power_level										: return "Tx Power Level"
			case .uncertainty											: return "Uncertainty"
			case .unread_alert_status									: return "Unread Alert Status"
			case .uri													: return "URI"
			case .user_control_point									: return "User Control Point"
			case .user_index											: return "User Index"
			case .uv_index												: return "UV Index"
			case .vo2_max												: return "VO2 Max"
			case .waist_circumference									: return "Waist Circumference"
			case .weight												: return "Weight"
			case .weight_measurement									: return "Weight Measurement"
			case .weight_scale_feature									: return "Weight Scale Feature"
			case .wind_chill											: return "Wind Chill"
		}
	}
}

//--------------------------------------------------------------------------------
//
//
//
//--------------------------------------------------------------------------------
enum org_bluetooth_descriptor: String {
	case characteristic_extended_properties		= "2900"
	case characteristic_user_description		= "2901"
	case client_characteristic_configuration	= "2902"
	case server_characteristic_configuration	= "2903"
	case characteristic_presentation_format		= "2904"
	case characteristic_aggregate_format		= "2905"
	case valid_range							= "2906"
	case external_report_reference				= "2907"
	case report_reference						= "2908"
	case number_of_digitals						= "2909"
	case value_trigger_setting					= "290A"
	case es_configuration						= "290B"
	case es_measurement							= "290C"
	case es_trigger								= "290D"
	case time_trigger_setting					= "290E"

	var UUID: CBUUID {
		return CBUUID(string: self.rawValue)
	}
	
	var title	: String {
		switch (self) {
		case .characteristic_extended_properties:	return "Characteristic Extended Properties"
		case .characteristic_user_description:		return "Characteristic User Description"
		case .client_characteristic_configuration:	return "Client Characteristic Configuration"
		case .server_characteristic_configuration:	return "Server Characteristic Configuration"
		case .characteristic_presentation_format:	return "Characteristic Presentation Format"
		case .characteristic_aggregate_format:		return "Characteristic Aggregate Format"
		case .valid_range:							return "Valid Range"
		case .external_report_reference:			return "External Report Reference"
		case .report_reference:						return "Report Reference"
		case .number_of_digitals:					return "Number of Digitals"
		case .value_trigger_setting:				return "Value Trigger Setting"
		case .es_configuration:						return "ES Configuration"
		case .es_measurement:						return "ES Measurement"
		case .es_trigger:							return "ES Trigger"
		case .time_trigger_setting:					return "Time Trigger Setting"
		}
	}
}

